export const COLORS = {
  ONE: "#5B7DD3",
  TWO: "#382F53",
  THREE: "#45434D",
};

export const ACTIONS = {
  SYNC: "SYNC",
  ASYNC: "ASYNC",
  MESSAGE: "MESSAGE",
  EVENT_LOOP: "EVENT_LOOP",
  REMOVE_FROM_WEB_API: "REMOVE_FROM_WEB_API",
  REMOVE_FROM_CALL_STACK: "REMOVE_FROM_CALL_STACK",
  REMOVE_FROM_MESSAGE_QUEUE: "REMOVE_FROM_MESSAGE_QUEUE",
};
